Update ccgcrv
ICOS-Carbon-Portal/jupyter-archive pull request #252
Opened 2022-11-16 15:00 UTC by altix

2022-11-17 12:24 UTC, claudiodonofrio requested changes
please change the code to make it more robust:
def get_data...... return statement

# Concatenate the data
    if df_ls:
        large_df = pd.concat(df_ls)
        large_df.sort_index(inplace=True)
        return (large_df, citation_ls)
    else:
        #return an empty dataframe
        return (pd.DataFrame(),'')

2022-11-17 16:43 UTC, claudiodonofrio approved these changes

2022-11-18 06:47 UTC, ukarst requested changes
The DOI for reference to Hazan et al. is (and probably was) not an active link. Consider the followig change:
For more information regarding data processing at ICOS ATC we refer to Hazan et al., Atmos. Meas. Tech., 9, 4719–4736, https://doi.org/10.5194/amt-9-4719-2016

2022-11-18 14:40 UTC, ukarst approved these changes

2022-11-22 08:59 UTC, merged